[versions]
kotest = "5.9.1"
kotlin = "2.1.21"
tuprolog = "1.0.4"
alchemist = "37.0.1"
ktor = "3.0.1"
openai = "4.0.1"
kotlinxPlugin = "2.1.0"
kotlinCoroutines = "1.10.1"
mockk = "1.13.17"
kaml = "0.77.0"
clikt = "5.0.1"
kotlinx = "1.8.1"
ktsearch = "2.4.1"
log4j = "2.24.3"
konsist = "0.17.3"
koin = "4.0.3"
kotestKoin = "1.3.0"

[libraries]
alchemist-api = { module = "it.unibo.alchemist:alchemist-api", version.ref = "alchemist" }
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
alchemist-swingui = { module = "it.unibo.alchemist:alchemist-swingui", version.ref = "alchemist" }
alchemist-ui-tooling = {module = "it.unibo.alchemist:alchemist-ui-tooling", version.ref = "alchemist" }
alchemist-euclidean-geometry = {module = "it.unibo.alchemist:alchemist-euclidean-geometry", version.ref = "alchemist" }
alchemist-maps = {module = "it.unibo.alchemist:alchemist-maps", version.ref = "alchemist" }
alchemist-physics = {module = "it.unibo.alchemist:alchemist-physics", version.ref = "alchemist" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-koin = { module = "io.kotest.extensions:kotest-extensions-koin", version.ref = "kotestKoin" }
tuprolog-full = { module = "it.unibo.tuprolog:2p-jvm", version.ref = "tuprolog" }
tuprolog-ide = { module = "it.unibo.tuprolog:ide", version.ref = "tuprolog" }
tuprolog-repl = { module = "it.unibo.tuprolog:repl-jvm", version.ref = "tuprolog" }
tuprolog-core = { module = "it.unibo.tuprolog:core-jvm", version.ref = "tuprolog" }
tuprolog-unify = { module = "it.unibo.tuprolog:unify-jvm", version.ref = "tuprolog" }
tuprolog-theory = { module = "it.unibo.tuprolog:theory-jvm", version.ref = "tuprolog" }
tuprolog-solve-classic = { module = "it.unibo.tuprolog:solve-classic-jvm", version.ref = "tuprolog" }
tuprolog-parser-core = { module = "it.unibo.tuprolog:parser-core-jvm", version.ref = "tuprolog" }
tuprolog-parser-theory = { module = "it.unibo.tuprolog:parser-theory-jvm", version.ref = "tuprolog" }
tuprolog-dsl-core = { module = "it.unibo.tuprolog:dsl-core-jvm", version.ref = "tuprolog" }
tuprolog-dsl-unify = { module = "it.unibo.tuprolog:dsl-unify-jvm", version.ref = "tuprolog" }
tuprolog-dsl-theory = { module = "it.unibo.tuprolog:dsl-theory-jvm", version.ref = "tuprolog" }
tuprolog-dsl-solve = { module = "it.unibo.tuprolog:dsl-solve-jvm", version.ref = "tuprolog" }
tuprolog-oop-lib = { module = "it.unibo.tuprolog:oop-lib-jvm", version.ref = "tuprolog" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
openai = { module = "com.aallam.openai:openai-client", version.ref = "openai" }
kotlin-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-json = { module = "org.apache.logging.log4j:log4j-layout-template-json", version.ref = "log4j" }
log4j-slf4j = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
ktsearch = { module = "com.jillesvangurp:search-client-jvm", version.ref = "ktsearch" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }

[bundles]
koin = [
    "koin-core",
    "koin-test"
]
kotlin-logging = [
    "log4j-json",
    "log4j-core",
    "log4j-api",
    "log4j-slf4j"
]
kotlin-testing = [
    "kotest-junit5-jvm",
    "kotest-assertions-core-jvm",
    "kotest-koin",
    "kotlin-mockk",
]
alchemist-api = [
    "alchemist",
    "alchemist-api",
]
alchemist-dev = [
    "alchemist-euclidean-geometry",
    "alchemist-maps",
    "alchemist-physics",
    "alchemist-ui-tooling",
    "alchemist-swingui",
]

[plugins]
dokka = "org.jetbrains.dokka:2.0.0"
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "3.1.7" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.86.2" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "3.1.2" }
publishOnCentral =  { id = "org.danilopianini.publish-on-central", version = "8.0.1"}
taskTree = { id = "com.dorongold.task-tree", version = "4.0.0" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinx = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinxPlugin"}
